services:
  - type: web
    name: cafe-bot
    runtime: python

    buildCommand: |
      pip install -r requirements.txt

    startCommand: |
      cd src && uvicorn main:app --host 0.0.0.0 --port $PORT